// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// SlugToURL is an autogenerated mock type for the SlugToURL type
type SlugToURL struct {
	mock.Mock
}

// URL provides a mock function with given fields: slug
func (_m *SlugToURL) URL(slug string) (string, error) {
	ret := _m.Called(slug)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLExists provides a mock function with given fields: slug
func (_m *SlugToURL) URLExists(slug string) (bool, error) {
	ret := _m.Called(slug)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
